"""empty message

Revision ID: 61666806f5e5
Revises: c4564d735dd1
Create Date: 2018-09-16 00:41:36.228111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61666806f5e5'
down_revision = 'c4564d735dd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('badge', sa.Column('extid', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('badge', 'extid')
    # ### end Alembic commands ###
