"""empty message

Revision ID: afcb62969b4b
Revises: 1b8348dacd48
Create Date: 2018-09-15 15:18:20.130287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afcb62969b4b'
down_revision = '1b8348dacd48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_history',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_name', sa.String(length=64), nullable=False),
    sa.Column('recipe_uri', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'timestamp')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_history')
    # ### end Alembic commands ###
