"""empty message

Revision ID: c4564d735dd1
Revises: afcb62969b4b
Create Date: 2018-09-15 20:53:44.546055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4564d735dd1'
down_revision = 'afcb62969b4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient', sa.Column('image', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredient', 'image')
    # ### end Alembic commands ###
