"""empty message

Revision ID: f20f54473174
Revises: 61666806f5e5
Create Date: 2018-09-16 01:18:25.694834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f20f54473174'
down_revision = '61666806f5e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_history', sa.Column('recipe_image_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_history', 'recipe_image_url')
    # ### end Alembic commands ###
